Hw04 auth
WeronikaNiemczyk/nodeJS-goit-2-6-hw pull request #3
Opened 2024-07-08 19:43 UTC by WeronikaNiemczyk

Przesyłam PR, przez przypadek zrobiłam jeden duzy commit do wiekszości plików. 
Opiszę co zostało zrobione:
1. Dodałam plik jwt.js, w którym jest logika odnośnie autoryzacji - bearer token
2. W index.js dodałam funkcje obsługujące logowanie, rejestrację oraz wyświetlanie danych aktywnego użytkownika
3. W jwt.js jest middleware, który sprawdza tokeny
4. W contacts.js dodałam endpointy
5. Utworzyłam plik salt.js, gdzie znalazła się logika odnośnie porównania haseł czy się zgadzają za pomocą soli z zastosowaniem bcrypt
6. Utworzyłam plik z modelem users w users-models.js

2024-07-09 12:27 UTC, KamilMr requested changes
Hej, wybierz czy chcesz uzywac passport czy twoja wlasne uwierzytelnienie :) Usuń co niepotrzebne i dodaj co potrzebne.

2024-07-09 12:27 UTC, KamilMr commented on salt.js
Ten plik jest ok do testów. Myśle że nie warto go umieszczać w tym repo. Mozesz stworzyc jakies inne repo gdzie bedziesz trzymac takie rzeczy albo sugeruje usunąć i zrobić commit np: "Remove salt.js file" i wtedy w historii git o ile nie usuniesz galezi zawsze bedzie ten kod dostepny.

2024-07-09 12:27 UTC, KamilMr commented on controlers/contacts/index.js
> +      return res.status(401).json({ message: "Not authorized" });
authMiddleware jus sprawdzilo czy jest authorized czy nie, czyli jesli tu jestesmy to user zostal pomyslnie uwierzytelniony

2024-07-09 12:27 UTC, KamilMr commented on middleware/jwt.js
Tu sama sprawdzasz token, nie uzywasz passport, czemu?
https://www.passportjs.org/packages/passport-jwt/

Brakuje tego passport.authenticate

2024-07-10 08:36 UTC, WeronikaNiemczyk commented
> Hej, wybierz czy chcesz uzywac passport czy twoja wlasne uwierzytelnienie :) Usuń co niepotrzebne i dodaj co potrzebne.

Poprawiłam, użyje passport, bo jednak łatwiejsze. To własne to znalazłam w internecie, że jest taki sposób bo sie troche pogubiłam z tym uwierzytelnieniem, już później nie byłam pewna co do czego. A teraz już chyba wiem ;)

2024-07-10 16:43 UTC, KamilMr approved these changes

2024-07-10 18:19 UTC, merged